#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone --quiet -j32 https://github.com/crDroidMod/android_prebuilts_clang_host_linux-x86_clang-5900059 -b 9.0 --depth=1 clang
git clone --quiet -j32 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-9.0.0_r49 --depth=1 aarch64
git clone --quiet -j32 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-9.0.0_r49 --depth=1 arm32
git clone --quiet -j32 https://github.com/Mhmmdfas/anykernel3 --depth=1 -b rolex anykernel3 && rm -rf any*/READ

CT="$(pwd)/clang/bin/clang"
GCC="$(pwd)/aarch64/bin/aarch64-linux-android-"
GCCARM="$(pwd)/arm32/bin/arm-linux-androideabi-"
curl -s -F chat_id=${chat_id} -F sticker="CAADBQADJAEAAn1Cwy6oClWEDGYAAQEWBA" https://api.telegram.org/bot${token}/sendSticker
curl -s -X POST https://api.telegram.org/bot${token}/sendMessage?chat_id=${chat_id} -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>// winxkernel //</b>%0ACompile Started"'!'"%0A<b>For device</b> <code>RIVA (Redmi 5A)</code>%0A<b>For Oreo/Pie</b>%0A<b>Under Commit</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)</code>%0A<b>Compiler</b> <code>$(${GCCARM}gcc --version | head -n 1)</code>%0A<b>Clang</b> <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0A<b>Started on</b> <code>$(date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=zantrash
export KBUILD_BUILD_HOST=Base77
export USE_CCACHE=1
export CACHE_DIR=~/.ccache

# Sprunge
function sprunge() {
    cat build.log | curl -F 'sprunge=<-' http://sprunge.us > link
    HASIL="$(cat link)"
}

# Fin Error
function finerr() {
        sprunge
        curl -s -X POST https://api.telegram.org/bot${token}/sendMessage?chat_id=${chat_id} -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s) | <b>Build logs</b> <a href='${HASIL}'>here</a>"
        exit 1
}
make -s -C $(pwd) O=out rolex_defconfig
make -s -C $(pwd) CC=${CT} CROSS_COMPILE_ARM32=${GCCARM} CROSS_COMPILE=${GCC} O=out -j32 -l12 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb anykernel3/zImage
sprunge
cd anykernel3
zip -r9 perf-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="${chat_id}" -F document=@"perf-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). <b>Logs</b> <a href='${HASIL}'>here</a> | #riva" https://api.telegram.org/bot${token}/sendDocument
cd ..
rm -rf out
rm -rf anykernel3/zImage
rm -rf anykernel3/*.zip
